name: moovapp
description: "Application de covoiturage universitaire Moov."
publish_to: 'none' # Ne pas publier sur pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# --- DÉPENDANCES DE L'APPLICATION ---
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.2
  http: ^1.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.1.1 
  shared_preferences: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png
  

  # --- DÉCLARATION DES POLICES ---
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700